//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public Nullable<int> adress_index { get; set; }
        public string adress_gorod { get; set; }
        public string adress_street { get; set; }
        public string adress_house { get; set; }
        public string adress_flat { get; set; }
        public string email { get; set; }
    }
}
