//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int id { get; set; }
        public string Kod_zakaz { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Kod_client { get; set; }
        public string Uslugi { get; set; }
        public string Status { get; set; }
        public string Date_zakrit { get; set; }
        public int Vremya { get; set; }
    }
}
