//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public string Kod { get; set; }
        public string DateOfCreating { get; set; }
        public string TimeOfCreating { get; set; }
        public Nullable<int> KodKlient { get; set; }
        public string Service { get; set; }
        public string Status { get; set; }
        public string DateOfClosing { get; set; }
        public string TImeOfRental { get; set; }
    }
}
