//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positions
    {
        public int ID_Employee { get; set; }
        public string Positions1 { get; set; }
        public string FullName { get; set; }
        public string Employee_Login { get; set; }
        public string Employee_Password { get; set; }
        public string Last_Entrance { get; set; }
        public string Type_Of_Entrance { get; set; }
    }
}
