//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ID { get; set; }
        public string Name_Of_Services { get; set; }
        public string Type_Of_Services { get; set; }
        public string Code_Of_Services { get; set; }
        public string Price { get; set; }
    }
}
